/*
* Copyright (c) 2022, Intel Corporation
*
* Permission is hereby granted, free of charge, to any person obtaining a
* copy of this software and associated documentation files (the "Software"),
* to deal in the Software without restriction, including without limitation
* the rights to use, copy, modify, merge, publish, distribute, sublicense,
* and/or sell copies of the Software, and to permit persons to whom the
* Software is furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
* THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
* OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*/
//!
//! \file     ddi_cp_caps_data.h
//! \brief    cp caps data file
//!

#ifndef __DDI_CP_CAPS_DATA_H__
#define __DDI_CP_CAPS_DATA_H__

#include "capstable_data_linux_definition.h"
#include "va_protected_content_private.h"

static AttribList attribList_VAProfileProtected_VAEntrypointProtectedContent
{
    {VAConfigAttribProtectedContentCipherAlgorithm,                 VA_PC_CIPHER_AES                                            },
    {VAConfigAttribProtectedContentCipherBlockSize,                 VA_PC_BLOCK_SIZE_128                                        },
    {VAConfigAttribProtectedContentCipherMode,                      VA_PC_CIPHER_MODE_CBC        | VA_PC_CIPHER_MODE_CTR        },
    {VAConfigAttribProtectedContentCipherSampleType,                VA_PC_SAMPLE_TYPE_FULLSAMPLE | VA_PC_SAMPLE_TYPE_SUBSAMPLE  },
    {VAConfigAttribProtectedContentUsage,                           VA_PC_USAGE_DEFAULT          | VA_PC_USAGE_WIDEVINE         },
    {(VAConfigAttribType)VAConfigAttribProtectedContentSessionType, VA_PC_SESSION_TYPE_DISPLAY   | VA_PC_SESSION_TYPE_TRANSCODE },
    {(VAConfigAttribType)VAConfigAttribProtectedContentSessionMode, VA_PC_SESSION_MODE_LITE      | VA_PC_SESSION_MODE_HEAVY     },
};

static ConfigDataList configDataList_VAProfileProtected_VAEntrypointProtectedContent_Base
{
    {VA_PC_SESSION_MODE_NONE, VA_PC_SESSION_TYPE_NONE, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CBC, VA_PC_SAMPLE_TYPE_FULLSAMPLE, VA_PC_USAGE_WIDEVINE},
    {VA_PC_SESSION_MODE_NONE, VA_PC_SESSION_TYPE_NONE, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CBC, VA_PC_SAMPLE_TYPE_SUBSAMPLE,  VA_PC_USAGE_WIDEVINE},
    {VA_PC_SESSION_MODE_NONE, VA_PC_SESSION_TYPE_NONE, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CTR, VA_PC_SAMPLE_TYPE_FULLSAMPLE, VA_PC_USAGE_WIDEVINE},
    {VA_PC_SESSION_MODE_NONE, VA_PC_SESSION_TYPE_NONE, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CTR, VA_PC_SAMPLE_TYPE_SUBSAMPLE,  VA_PC_USAGE_WIDEVINE},

    {VA_PC_SESSION_MODE_LITE, VA_PC_SESSION_TYPE_DISPLAY, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CBC, VA_PC_SAMPLE_TYPE_FULLSAMPLE, VA_PC_USAGE_DEFAULT},
    {VA_PC_SESSION_MODE_LITE, VA_PC_SESSION_TYPE_DISPLAY, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CBC, VA_PC_SAMPLE_TYPE_SUBSAMPLE,  VA_PC_USAGE_DEFAULT},
    {VA_PC_SESSION_MODE_LITE, VA_PC_SESSION_TYPE_DISPLAY, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CTR, VA_PC_SAMPLE_TYPE_FULLSAMPLE, VA_PC_USAGE_DEFAULT},
    {VA_PC_SESSION_MODE_LITE, VA_PC_SESSION_TYPE_DISPLAY, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CTR, VA_PC_SAMPLE_TYPE_SUBSAMPLE,  VA_PC_USAGE_DEFAULT},
    {VA_PC_SESSION_MODE_LITE, VA_PC_SESSION_TYPE_TRANSCODE, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CBC, VA_PC_SAMPLE_TYPE_FULLSAMPLE, VA_PC_USAGE_DEFAULT},
    {VA_PC_SESSION_MODE_LITE, VA_PC_SESSION_TYPE_TRANSCODE, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CBC, VA_PC_SAMPLE_TYPE_SUBSAMPLE,  VA_PC_USAGE_DEFAULT},
    {VA_PC_SESSION_MODE_LITE, VA_PC_SESSION_TYPE_TRANSCODE, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CTR, VA_PC_SAMPLE_TYPE_FULLSAMPLE, VA_PC_USAGE_DEFAULT},
    {VA_PC_SESSION_MODE_LITE, VA_PC_SESSION_TYPE_TRANSCODE, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CTR, VA_PC_SAMPLE_TYPE_SUBSAMPLE,  VA_PC_USAGE_DEFAULT},

    {VA_PC_SESSION_MODE_HEAVY, VA_PC_SESSION_TYPE_DISPLAY, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CBC, VA_PC_SAMPLE_TYPE_FULLSAMPLE, VA_PC_USAGE_DEFAULT},
    {VA_PC_SESSION_MODE_HEAVY, VA_PC_SESSION_TYPE_DISPLAY, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CBC, VA_PC_SAMPLE_TYPE_SUBSAMPLE,  VA_PC_USAGE_DEFAULT},
    {VA_PC_SESSION_MODE_HEAVY, VA_PC_SESSION_TYPE_DISPLAY, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CTR, VA_PC_SAMPLE_TYPE_FULLSAMPLE, VA_PC_USAGE_DEFAULT},
    {VA_PC_SESSION_MODE_HEAVY, VA_PC_SESSION_TYPE_DISPLAY, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CTR, VA_PC_SAMPLE_TYPE_SUBSAMPLE,  VA_PC_USAGE_DEFAULT},
    {VA_PC_SESSION_MODE_HEAVY, VA_PC_SESSION_TYPE_TRANSCODE, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CBC, VA_PC_SAMPLE_TYPE_FULLSAMPLE, VA_PC_USAGE_DEFAULT},
    {VA_PC_SESSION_MODE_HEAVY, VA_PC_SESSION_TYPE_TRANSCODE, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CBC, VA_PC_SAMPLE_TYPE_SUBSAMPLE,  VA_PC_USAGE_DEFAULT},
    {VA_PC_SESSION_MODE_HEAVY, VA_PC_SESSION_TYPE_TRANSCODE, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CTR, VA_PC_SAMPLE_TYPE_FULLSAMPLE, VA_PC_USAGE_DEFAULT},
    {VA_PC_SESSION_MODE_HEAVY, VA_PC_SESSION_TYPE_TRANSCODE, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CTR, VA_PC_SAMPLE_TYPE_SUBSAMPLE,  VA_PC_USAGE_DEFAULT},
};

static ConfigDataList configDataList_VAProfileProtected_VAEntrypointProtectedContent_Stout_Base
{
    {VA_PC_SESSION_MODE_STOUT, VA_PC_SESSION_TYPE_DISPLAY, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CBC, VA_PC_SAMPLE_TYPE_FULLSAMPLE, VA_PC_USAGE_DEFAULT},
    {VA_PC_SESSION_MODE_STOUT, VA_PC_SESSION_TYPE_DISPLAY, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CBC, VA_PC_SAMPLE_TYPE_SUBSAMPLE,  VA_PC_USAGE_DEFAULT},
    {VA_PC_SESSION_MODE_STOUT, VA_PC_SESSION_TYPE_DISPLAY, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CTR, VA_PC_SAMPLE_TYPE_FULLSAMPLE, VA_PC_USAGE_DEFAULT},
    {VA_PC_SESSION_MODE_STOUT, VA_PC_SESSION_TYPE_DISPLAY, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CTR, VA_PC_SAMPLE_TYPE_SUBSAMPLE,  VA_PC_USAGE_DEFAULT},
};

static ConfigDataList configDataList_VAProfileProtected_VAEntrypointProtectedContent_Stout_Transcode
{
    {VA_PC_SESSION_MODE_STOUT, VA_PC_SESSION_TYPE_TRANSCODE, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CBC, VA_PC_SAMPLE_TYPE_FULLSAMPLE, VA_PC_USAGE_DEFAULT},
    {VA_PC_SESSION_MODE_STOUT, VA_PC_SESSION_TYPE_TRANSCODE, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CBC, VA_PC_SAMPLE_TYPE_SUBSAMPLE,  VA_PC_USAGE_DEFAULT},
    {VA_PC_SESSION_MODE_STOUT, VA_PC_SESSION_TYPE_TRANSCODE, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CTR, VA_PC_SAMPLE_TYPE_FULLSAMPLE, VA_PC_USAGE_DEFAULT},
    {VA_PC_SESSION_MODE_STOUT, VA_PC_SESSION_TYPE_TRANSCODE, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CTR, VA_PC_SAMPLE_TYPE_SUBSAMPLE,  VA_PC_USAGE_DEFAULT},
    {VA_PC_SESSION_MODE_STOUT, VA_PC_SESSION_TYPE_TRANSCODE, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CBC, VA_PC_SAMPLE_TYPE_FULLSAMPLE, VA_PC_USAGE_SECURE_COMPUTE},
    {VA_PC_SESSION_MODE_STOUT, VA_PC_SESSION_TYPE_TRANSCODE, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CBC, VA_PC_SAMPLE_TYPE_SUBSAMPLE,  VA_PC_USAGE_SECURE_COMPUTE},
    {VA_PC_SESSION_MODE_STOUT, VA_PC_SESSION_TYPE_TRANSCODE, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CTR, VA_PC_SAMPLE_TYPE_FULLSAMPLE, VA_PC_USAGE_SECURE_COMPUTE},
    {VA_PC_SESSION_MODE_STOUT, VA_PC_SESSION_TYPE_TRANSCODE, VA_PC_CIPHER_AES, VA_PC_BLOCK_SIZE_128, VA_PC_CIPHER_MODE_CTR, VA_PC_SAMPLE_TYPE_SUBSAMPLE,  VA_PC_USAGE_SECURE_COMPUTE}
};

static AttribList attribList_VAProfileProtected_VAEntrypointProtectedTEEComm
{
    {(VAConfigAttribType)VAConfigAttribProtectedContentSessionMode, VA_PC_SESSION_MODE_NONE},
    {(VAConfigAttribType)VAConfigAttribProtectedContentSessionType, VA_PC_SESSION_TYPE_NONE},
};

static ConfigDataList configDataList_VAProfileProtected_VAEntrypointProtectedTEEComm
{
    {VA_PC_SESSION_MODE_NONE, VA_PC_SESSION_TYPE_NONE, 0, 0, 0, 0, 0}
};

static EntrypointData entrypointMap_VAProfileProtected_VAEntrypointProtectedContent_Data
{
    &attribList_VAProfileProtected_VAEntrypointProtectedContent,
    &configDataList_VAProfileProtected_VAEntrypointProtectedContent_Base,
    nullptr // CP do not require
};

static EntrypointData entrypointMap_VAProfileProtected_VAEntrypointProtectedTEEComm_Data
{
    &attribList_VAProfileProtected_VAEntrypointProtectedTEEComm,
    &configDataList_VAProfileProtected_VAEntrypointProtectedTEEComm,
    nullptr // CP do not require
};

static EntrypointMap entrypointMap_VAProfileProtected
{
    {VAEntrypointProtectedContent, &entrypointMap_VAProfileProtected_VAEntrypointProtectedContent_Data},
    {VAEntrypointProtectedTEEComm, &entrypointMap_VAProfileProtected_VAEntrypointProtectedTEEComm_Data}
};

static ProfileMap profileMap_VAProfileProtected
{
    {VAProfileProtected, &entrypointMap_VAProfileProtected}
};

typedef std::map<std::vector<VAProfile>, std::vector<uint32_t>> CodecEncryptionType;

static CodecEncryptionType DecodeEncryptionType = 
{
    {{VAProfileH264High, VAProfileH264Main, VAProfileH264ConstrainedBaseline}, 
     {VA_ENCRYPTION_TYPE_FULLSAMPLE_CTR, VA_ENCRYPTION_TYPE_SUBSAMPLE_CTR, VA_ENCRYPTION_TYPE_SUBSAMPLE_CBC}},

    {{VAProfileHEVCMain,       VAProfileHEVCMain10,    VAProfileHEVCMain12,     VAProfileHEVCMain422_10,
      VAProfileHEVCMain422_12, VAProfileHEVCMain444,   VAProfileHEVCMain444_10, VAProfileHEVCMain444_12,
      VAProfileHEVCSccMain,    VAProfileHEVCSccMain10, VAProfileHEVCSccMain444},
     {VA_ENCRYPTION_TYPE_FULLSAMPLE_CTR, VA_ENCRYPTION_TYPE_SUBSAMPLE_CTR, VA_ENCRYPTION_TYPE_SUBSAMPLE_CBC}},

    {{VAProfileVP9Profile0, VAProfileVP9Profile2, VAProfileVP9Profile1, VAProfileVP9Profile3},
     {VA_ENCRYPTION_TYPE_SUBSAMPLE_CTR, VA_ENCRYPTION_TYPE_SUBSAMPLE_CBC}},

    {{VAProfileAV1Profile0},
     {VA_ENCRYPTION_TYPE_SUBSAMPLE_CTR, VA_ENCRYPTION_TYPE_SUBSAMPLE_CBC}}
};

#endif //__DDI_CP_CAPS_H__