/*
// Copyright (C) 2011-2021 Intel Corporation
//
// Licensed under the Apache License,Version 2.0(the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
*/
//!
//! \file     codechal_user_settings_ext.h
//! \brief    Common Codec service for proprietary use
//! \details  Common Codec service for proprietary use across different platform
//!
#ifndef __CODECHAL_USER_SETTINGS_EXT_H__
#define __CODECHAL_USER_SETTINGS_EXT_H__

#include "media_user_settings_mgr.h"

#define __CODECHAL_USER_FEATURE_KEY_START_ID 5120

//!
//! \brief User Feature Value IDs
//!
typedef enum _CODECHAL_USER_FEATURE_VALUE_ID
{
    __CODECHAL_USER_FEATURE_KEY_INVALID_ID = __CODECHAL_USER_FEATURE_KEY_START_ID,
    __MEDIA_USER_FEATURE_VALUE_FULSIM_IN_USE_ID,
    __MEDIA_USER_FEATURE_VALUE_HUC_KERNEL_DEBUG_LEVEL_ID,
    __MEDIA_USER_FEATURE_VALUE_AES_NATIVE_ENABLE_ID,
    __MEDIA_USER_FEATURE_VALUE_HEVC_HYBRID_DISABLE_DEBLOCK_ID,
    __MEDIA_USER_FEATURE_VALUE_HEVC_HYBRID_DISABLE_SAO_ID,
    __MEDIA_USER_FEATURE_VALUE_HEVC_HYBRID_DISABLE_KERNEL_EXECUTION_ID,
    __MEDIA_USER_FEATURE_VALUE_HEVC_HYBRID_SLICE_SHUTDOWN_ENABLE_ID,
    __MEDIA_USER_FEATURE_VALUE_HEVC_HYBRID_DECODE_WPP_BASED_MT_ENABLE_ID,
    __MEDIA_USER_FEATURE_VALUE_HEVC_HYBRID_WORKER_THREAD_COUNT_ID,
    __MEDIA_USER_FEATURE_VALUE_HEVC_HYBRID_DECODE_FRAME_BASED_MT_ENABLE_ID,
    __MEDIA_USER_FEATURE_VALUE_HEVC_HYBRID_COMPRESSED_BUFFER_QUEUE_SIZE_ID,
    __MEDIA_USER_FEATURE_VALUE_HEVC_HYBRID_HOST_PLANE_BUFFER_QUEUE_SIZE_ID,
    __MEDIA_USER_FEATURE_VALUE_HEVC_HYBRID_LCU_DEPENDENCY_CHECK_NUM_ID,
    __MEDIA_USER_FEATURE_VALUE_HEVC_HYBRID_DECODE_MT_ENABLED_REPORT_ID,
    __MEDIA_USER_FEATURE_VALUE_HEVC_HYBRID_SYNC_THREADS_ID,
    __MEDIA_USER_FEATURE_VALUE_VP9_HYBRID_DECODE_DUMP_ID,
    __MEDIA_USER_FEATURE_VALUE_VP9_HYBRID_DECODE_LOAD_GOLDEN_ID,
    __MEDIA_USER_FEATURE_VALUE_VP9_HYBRID_DECODE_DISABLE_DEBLOCK_ID,
    __MEDIA_USER_FEATURE_VALUE_VP9_HYBRID_DECODE_THREAD_NUMBER_ID,
    __MEDIA_USER_FEATURE_VALUE_VP9_HYBRID_DECODE_DDI_BUFFER_QUEUE_SIZE_ID,
    __MEDIA_USER_FEATURE_VALUE_VP9_HYBRID_EARLY_DECODE_BUFFER_NUM_ID,
    __MEDIA_USER_FEATURE_VALUE_VP9_HYBRID_DECODE_HOST_BUFFER_NUMBER_ID,
    __MEDIA_USER_FEATURE_VALUE_VP9_HYBRID_DECODE_INTRA_PRED_MODE_LUMA_ID,
    __MEDIA_USER_FEATURE_VALUE_VP9_HYBRID_DECODE_INTRA_PRED_MODE_CHROMA_ID,
    __MEDIA_USER_FEATURE_VALUE_VP9_HYBRID_SLICE_SHUTDOWN_ENABLE_ID,
    __MEDIA_USER_FEATURE_VALUE_VP8_ENCODE_ENABLE_ID,
    __MEDIA_USER_FEATURE_VALUE_AV1_ADAPTIVE_ROUNDING_ENABLE_ID,
    __MEDIA_USER_FEATURE_VALUE_AV1_RDO_ENABLE_ID,
    __MEDIA_USER_FEATURE_VALUE_ENABLE_NONDEFAULT_MAPPING_ID,
    __MEDIA_USER_FEATURE_VALUE_ENABLE_SW_BACK_ANNOTATION_ID,
    __MEDIA_USER_FEATURE_VALUE_ENABLE_CC_STITCHING_ID,
#if (_DEBUG || _RELEASE_INTERNAL)
    __MEDIA_USER_FEATURE_VALUE_ENABLE_SW_STITCHING_ID,
    __MEDIA_USER_FEATURE_VALUE_AV1_USE_EXT_COSTS_ID,
    __MEDIA_USER_FEATURE_VALUE_AV1_EXT_COSTS_FILE_ID,
#endif
    __MEDIA_USER_FEATURE_VALUE_HEVC_RDO_ENABLE_ID,
    __MEDIA_USER_FEATURE_VALUE_MAP_AVC_GUID_TO_VDENC_ID,
    __MEDIA_USER_FEATURE_VALUE_MAP_VDENC_GUID_TO_AVC_ID,
    __MEDIA_USER_FEATURE_VALUE_HUC_ENCRYPT_MODE_ID,
    __MEDIA_USER_FEATURE_VALUE_DECRYPT_DECODE_IN_ID,
    __MEDIA_USER_FEATURE_VALUE_DECRYPT_DECODE_OUT_ID,
    __MEDIA_USER_FEATURE_VALUE_DECRYPT_DELAY_START_ID,
    __MEDIA_USER_FEATURE_VALUE_DECRYPT_DELAY_STEP_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_PLATFORM_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_BYPASS_FULSIM_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_SIMULESS_USEAPPHEADER_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_SIMULESS_DUMPENABLE_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_SIMULESS_DUMPPATH_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_SIMULESS_LOGENABLE_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_SIMULESS_LOGPATH_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_SIMULESS_DLL_PATH_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_STEPPING_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_GT_SKU_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_AUBLOAD_COMMAND_LINE_OPTIONS_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_AUBLOAD_DIRECTORY_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_OUTPUT_DIRECTORY_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_DEBUG_OUTPUT_ENABLE_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_PAVPC_MMIO_GT_SETTING_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_PERF_TEST_ENABLE_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_AUBCAPTURE_ENABLE_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_PATHLIST_ENABLE_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_RESET_GFXADDR_PER_CONTEXT_DISABLE_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_AUBCAPTURE_BMP_DUMP_ENABLE_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_AUBCAPTURE_RECON_DUMP_ENABLE_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_ENABLE_FRAME_NUM_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_EXECLIST_ENABLE_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_VE_SCHEDULE_FIXED_MODE_ENABLE_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_ENABLE_VIRTUAL_ENGINE_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_ENABLE_MEM_TRACE_ID,
    __MEDIA_USER_FEATURE_VALUE_MEDIASOLO_ENABLE_LOCAL_MEM_ID,
    __MEDIA_USER_FEATURE_VALUE_ENCODE_MODE_ID,
    __MEDIA_USER_FEATURE_VALUE_ENCODE_DOWNSCALED_RATIO,
    __MEDIA_USER_FEATURE_VALUE_MV_GRID_REF0_SURFACE_DIRECTORY_ID,
    __MEDIA_USER_FEATURE_VALUE_MV_GRID_REF1_SURFACE_DIRECTORY_ID,
    __MEDIA_USER_FEATURE_VALUE_ENCODE_VDAQM_ENABLE_ID,
    __CODECHAL_USER_FEATURE_KEY_MAX_ID,
} CODECHAL_USER_FEATURE_VALUE_ID;

#define CODECHAL_NUM_USERFEATURE_KEY_VALUES (__CODECHAL_USER_FEATURE_KEY_MAX_ID - __CODECHAL_USER_FEATURE_KEY_INVALID_ID - 1)

class CodechalUserSettingsMgr : public MediaUserSettingsMgr
{
public:
    //!
    //! \brief    Init Codec proprietary User feature key table
    //!
    CodechalUserSettingsMgr();

    //!
    //! \brief    Destroy Codec proprietary User feature key table
    //!
    virtual ~CodechalUserSettingsMgr();
};

#endif // __CODECHAL_USER_SETTINGS_EXT_H__
