/*===================== begin_copyright_notice ==================================

INTEL CONFIDENTIAL
Copyright 2023
Intel Corporation All Rights Reserved.

The source code contained or described herein and all documents related to the
source code ("Material") are owned by Intel Corporation or its suppliers or
licensors. Title to the Material remains with Intel Corporation or its suppliers
and licensors. The Material contains trade secrets and proprietary and confidential
information of Intel or its suppliers and licensors. The Material is protected by
worldwide copyright and trade secret laws and treaty provisions. No part of the
Material may be used, copied, reproduced, modified, published, uploaded, posted,
transmitted, distributed, or disclosed in any way without Intel's prior express
written permission.

No license under any patent, copyright, trade secret or other intellectual
property right is granted to or conferred upon you by disclosure or delivery
of the Materials, either expressly, by implication, inducement, estoppel
or otherwise. Any license under such intellectual property rights must be
express and approved by Intel in writing.

File Name: cp_hal_gsc_defs.h

Abstract:
structure definations for GSC HAL for PAVP functions

Environment:
OS agnostic - should support - Wihdows, Linux, Android
Platform: Should support from DashG-1 onwards

Notes:
Due to open source restrictions, GSC(Graphics Security Controller)
has been replaced with RTE(Root Trust Engine) in many files

======================= end_copyright_notice ==================================*/

#ifndef __CP_HAL_GSC_DEFS_H__
#define __CP_HAL_GSC_DEFS_H__

// GSC command require pack(1)
#pragma pack(1)
typedef struct __GSC_HEADER_EXTENSION
{ 
    uint32_t extensiontype      : 16;   //Extension type
    uint32_t extension_length   : 16;   //Extension length in bytes. Including the extension header. For an extension with 0 sized payload, extension length will be 8.
    uint32_t reserved           : 31;   //Reserved
    uint32_t extension_exists   : 1;    //0: If this is the last extension and 1: If there's an additional extension after this one
    uint8_t extension_payload[];        //Extension payload
} GSC_HEADER_EXTENSION;

typedef struct __GSC_CS_MEMORY_HEADER
{
    union
    {
        struct
        {
            uint32_t validity_marker;               // Sanity check for FW and SW to know that they are looking at an actual HECI command and not some arbitrary address in memory, value : 0xA578875A
        };
        uint32_t Value;
    } DW0;

    union
    {
        struct
        {
            uint32_t gsc_address : 8;               // Route the message to the expected FW HECI client.
            uint32_t reserved_1 : 8;
            uint32_t header_version : 16;           // To distinguish the GSC HECI header contents in case it gets updated in the future.
        };
        uint32_t Value;
    } DW1;

    union
    {
        struct
        {
            uint64_t host_session_handle : 64;      // Generated by host and used to identify which SW context is sending this message.
        };
        uint32_t Value[2];
    } DW2_3;

    union
    {
        struct
        {
            uint64_t gsc_message_handle : 64;       // GSC generated handle to distinguish which message is being queried. This handle is a random number.
        };
        uint32_t Value[2];
    } DW4_5;

    union
    {
        struct
        {
            uint32_t message_size : 20;             // Size of the message including the header and extension in memory.
            uint32_t reserved_2 : 12;
        };
        uint32_t Value;
    } DW6;

    union
    {
        struct
        {
            uint32_t pending : 1;                   // If this bit is set, this means the command is not complete. SW requires to send the command again until this bit is cleared. This field is only used in response messages.
            uint32_t session_clanup : 1;            // This bit can only be set by host. Host will set it when a session is terminated.
                                                    // When GSC FW receives it, it will clean up all the resources that were allocated for the specific Host session handle.
                                                    // When this bit is set, there will be no payload after the GSC CS Memory header.
            uint32_t flags : 14;
            uint32_t extension_size : 16;           // If it has a non-zero value, there is an extension or extensions following the GSC CS memory header, before the payload. 
                                                    // This field defines the size of the extensions in bytes.
        };
        uint32_t Value;
    } DW7;

    union
    {
        struct
        {
            uint32_t status;                        // This field holds the CS header level status. It is used to indicate header level errors - invalid GSC address, invalid GSC message handle, etc.
        };
        uint32_t Value;
    } DW8;

} GSC_CS_MEMORY_HEADER;
#pragma pack()

#endif // __CP_HAL_GSC_DEFS_H__
