/*
//               INTEL CORPORATION PROPRIETARY INFORMATION
// This software is supplied under the terms of a license agreement or
// nondisclosure agreement with Intel Corporation and may not be copied
// or disclosed except in accordance with the terms of that agreement.
//        Copyright (c) 2010-2013 Intel Corporation. All Rights Reserved.
//
*/
#ifndef _INTEL_PAVP_CORE_API_H
#define _INTEL_PAVP_CORE_API_H

#if WDDM_LINUX
#include "windows.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif

#ifdef _WIN32
#include <minwindef.h>
#else //
#include "cp_os_defs.h"
#endif // _WINDOWS

#include "intel_pavp_types.h"

/*
**    GUID defining the Intel PAVP Device extension
**    See PAVP API/DDI design for more information
**    {7460004-7533-4E1A-B8E3-FF206BF5CE47}
*/

#pragma pack(push)
#pragma pack(8)

typedef enum
{
    PAVP_MEMORY_PROTECTION_NONE     = 0,
    PAVP_MEMORY_PROTECTION_LITE     = 1,
    PAVP_MEMORY_PROTECTION_STATIC   = 2,
    PAVP_MEMORY_PROTECTION_DYNAMIC  = 4
} PAVP_MEMORY_PROTECTION_MASK;

typedef enum
{
    PAVP_KEY_EXCHANGE_INVALID       = 0,
//    PAVP_KEY_EXCHANGE_CANTIGA       = 1, // deprecated
//    PAVP_KEY_EXCHANGE_EAGLELAKE     = 2, // deprecated
    PAVP_KEY_EXCHANGE_HEAVY         = 4,
//    PAVP_KEY_EXCHANGE_IRONLAKE      = 8, // deprecated
    PAVP_KEY_EXCHANGE_ISOLATED_DECODE = 8,
    PAVP_KEY_EXCHANGE_DAA             = 16,
    PAVP_KEY_EXCHANGE_RSA             = 32,
    PAVP_KEY_EXCHANGE_STOUT           = 64
} PAVP_KEY_EXCHANGE_MASK;

// PAVP_SESSION_TYPE_DESCRIPTION
typedef enum
{
    PAVP_SESSION_TYPE_INVALID       = 0,
    // Available session types.
    PAVP_SESSION_TYPE_DECODE        = 1,
    PAVP_SESSION_TYPE_TRANSCODE     = 2,
    PAVP_SESSION_TYPE_WIDI          = 3,
} PAVP_SESSION_TYPE;

// PAVP_SESSION_MODE_DESCRIPTION
typedef enum
{
    PAVP_SESSION_MODE_INVALID   = 0,
    // Available session modes.
    PAVP_SESSION_MODE_LITE      = 1, // Lite Mode
    PAVP_SESSION_MODE_HEAVY     = 2, // Heavy Mode
    PAVP_SESSION_MODE_ISO_DEC   = 3, // Isolated Decode Mode [Decoder(MFX),Display and VEBOX engines are allowed to operate on encrypted content]
    PAVP_SESSION_MODE_STOUT     = 4, // Isolated Decode with Authenticated EU [Decoder(MFX), Display and HW-signed kernels are allowed to operate on encrypted content]
    PAVP_SESSION_MODE_THV_D     = 5, // Isolated Display/Threadville-Display [Only the display HW that has the key is allowed to operate on encrypted content]
    PAVP_SESSION_MODE_HUC_GUARD = 6  // HuC Signed cmd buff [Only command buffers that have been generated by the HuC (instead of UMD) are allowed to operate on the content]
} PAVP_SESSION_MODE;

extern const char* PavpSessionType2Str(PAVP_SESSION_TYPE Type);

extern const char* PavpSessionMode2Str(PAVP_SESSION_MODE Mode);

typedef struct tagPAVP_QUERY_CAPS
{
    UINT AvailableMemoryProtection;     // Indicates supported protection modes.
    UINT AvailableKeyExchangeProtocols; // Indicates supported key exchange method.
    UINT Reserved1;
    PAVP_MEMORY_PROTECTION_MASK     eCurrentMemoryMode; // Only 1 bit set.
    UINT Reserved2;
} PAVP_QUERY_CAPS;

typedef struct tagPAVP_QUERY_CAPS2
{
    UINT AvailableMemoryProtection;     // Indicates supported protection modes.
    UINT AvailableKeyExchangeProtocols; // Indicates supported key exchange method.
    UINT Reserved1;
    PAVP_MEMORY_PROTECTION_MASK     eCurrentMemoryMode; // Only 1 bit set.
    UINT Reserved2;
    UINT AvailableSessionTypes;         // Indicates decode / transcode.
    UINT AvailableEncryptionTypes;      // Indicates none/CTR/CBC AES types.
    UINT AvailableCounterTypes;         // Indicates available HW counter bits.
} PAVP_QUERY_CAPS2;

// PAVP_FUNCTION_ID use in KeyExchange
typedef enum tagPAVP_FUNCTION_ID
{
    PAVP_FUNCTION_ID_NONE      = 0x0,
    PAVP_KEY_EXCHANGE          = 0x200,
//    PAVP_USE_PROTECTED_MEMORY  = 0x201,
//    PAVP_GET_CONNECTION_STATE  = 0x202,
    PAVP_GET_FRESHNESS         = 0x203,
    PAVP_SET_FRESHNESS         = 0x204,
    PAVP_SET_WINDOW_POSITION   = 0x205,
//    PAVP_SET_MEMORY_MODE       = 0x206,
//    PAVP_SET_PLANE_ENABLE      = 0x208,
    PAVP_GET_FRESHNESS_ENCRYPT = 0x209,
    PAVP_SET_FRESHNESS_ENCRYPT = 0x20A,
    PAVP_SET_STREAM_KEY        = 0x20B,
    PAVP_ME_PASS_THROUGH       = 0x20C,
    PAVP_GET_SESSION_ID        = 0x20D,
    PAVP_TERMINATE_SESSION_ID  = 0x20E,
    PAVP_RESERVE_SESSION_SLOT  = 0x20F
} PAVP_FUNCTION_ID;

// Device creation parameters.
typedef struct tagPAVP_CREATE_DEVICE
{
    PAVP_KEY_EXCHANGE_MASK    eDesiredKeyExchangeMode;  // Only one bit should be set.
} PAVP_CREATE_DEVICE, *PPAVP_CREATE_DEVICE;

typedef struct tagPAVP_CREATE_DEVICE2
{
    DWORD                   eDesiredKeyExchangeMode : 16;  // Only one bit should be set.
    DWORD                   PavpVersion             :  8;  // For version 0, struct is just 32-bits of PAVP_KEY_EXCHANGE_MASK.
    DWORD                   ePavpSessionType        :  8;  // Only one bit should be set.
} PAVP_CREATE_DEVICE2, *PPAVP_CREATE_DEVICE2;

// Fixed key exchange parameters.
typedef struct tagPAVP_FIXED_EXCHANGE_PARAMS
{
    DWORD   FixedKey[4];
    DWORD   SessionKey[4];
} PAVP_FIXED_EXCHANGE_PARAMS;

// PAVP get freshness struct.
typedef struct tagPAVP_GET_FRESHNESS_PARAMS
{
    DWORD   Freshness[4];
} PAVP_GET_FRESHNESS_PARAMS;

#if defined(_WINDEF_)
typedef struct tagPAVP_SET_WINDOW_POSITION_PARAMS
{
    RECT WindowPosition;
    RECT VisibleContent;
    HDC  hdcMonitorId;
} PAVP_SET_WINDOW_POSITION_PARAMS;
#endif

typedef enum
{
    PAVP_SET_KEY_DECRYPT    = 0, // Update Sn_d.
    PAVP_SET_KEY_ENCRYPT    = 1, // Update Sn_e.
    PAVP_SET_KEY_BOTH       = 2, // Update both Sn_d and Sn_e.
    PAVP_SET_KEY_WYSIWYS    = 4, // Enable heavy mode and update Sn_d (bitmap).
    PAVP_SET_KEY_ROTATION   = 5  // Update Sn_d and then Rotate Sn_d.
} PAVP_SET_KEY_TYPE;

typedef struct tagPAVP_SET_STREAM_KEY_PARAMS
{
    PAVP_SET_KEY_TYPE   StreamType;
    DWORD               EncryptedDecryptKey[4];
    union {
        DWORD           EncryptedEncryptKey[4];
        DWORD           EncryptedDecryptRotationKey[4];
    };
} PAVP_SET_STREAM_KEY_PARAMS;

typedef struct tagPAVP_ENCRYPTION_MODE
{
    PAVP_ENCRYPTION_TYPE    eEncryptionType;
    PAVP_COUNTER_TYPE       eCounterMode;
} PAVP_ENCRYPTION_MODE;

#pragma pack(pop)

#ifdef __cplusplus
}
#endif

#endif // _INTEL_PAVP_CORE_API_H
