/*
// Copyright (C) 2011-2022 Intel Corporation
//
// Licensed under the Apache License,Version 2.0(the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
*/
//!
//! \file     cp_user_settings_mgr_ext.cpp
//! \brief    Common CP service for proprietary use
//! \details  Common CP service for proprietary use across different platform
//!

#include "mos_util_user_interface.h"
#include "cp_user_settings_mgr_ext.h"
#include "cp_debug.h"

MOS_USER_FEATURE_VALUE cpUserFeatureKeyDescFields[CP_NUM_USERFEATURE_KEY_VALUES] =
    {
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_FIRST_KEY_EXCHANGE_IS_RSA_ID,
            __MEDIA_USER_FEATURE_VALUE_FIRST_KEY_EXCHANGE_IS_RSA,
            __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
            __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
            "CP",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_UINT32,
            "0",
            "Not Reported : Tested on 15.36 BDW."),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_CP_REPORTS_ENABLED_ID,
            __MEDIA_USER_FEATURE_VALUE_CP_REPORTS_ENABLED,
            __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
            __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
            "CP",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_UINT32,
            "0",
            "Required in order to dump out CP related user feature keys, in DXVA report."),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_HAS_PAVP_CTRL_ID,
            __MEDIA_USER_FEATURE_VALUE_HAS_PAVP_CTRL,
            __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
            __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
            "CP",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_UINT32,
            "3",
            "Used for Presilicon Key Exchange."),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_ARBITRATOR_SESSION_ENABLED_ID,
            __MEDIA_USER_FEATURE_VALUE_ARBITRATOR_SESSION_ENABLED,
            __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
            __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
            "CP",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_UINT32,
            "0",
            "Value Arbitrator Session Enable."),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_PAVP_PCH_HAL_UNIFIED_ENABLED_ID,
            __MEDIA_USER_FEATURE_VALUE_PAVP_PCH_HAL_UNIFIED_ENABLED,
            __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
            __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
            "CP",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_UINT32,
            "1",
            "PAVP PCH HAL Unified Enable."),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_ENCRYPTION_MODE_ID,
            __MEDIA_USER_FEATURE_VALUE_ENCRYPTION_MODE,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            "CP",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_UINT32,
            "0",
            "Expected Values in case. PAVP being used : 2. PAVP not is use : 0."),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_EVENT_PROVIDER_REFCOUNT_ID,
            "CP Event Provider Reference Count",
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            "CP",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_UINT32,
            "0",
            "CP Event Provider Reference Count"),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_ENCRYPTION_TYPE_ID,
            __MEDIA_USER_FEATURE_VALUE_ENCRYPTION_TYPE,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            "Report",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_UINT32,
            "0",
            "Expected Values."),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_PAVP_KEY_EXCHANGE_ID,
            __MEDIA_USER_FEATURE_VALUE_PAVP_KEY_EXCHANGE,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            "Report",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_UINT32,
            "0",
            "User feature that highlights Key Exchange type. EPID Lite: 16. EPID Heavy: 4. RSA DX11 Lite: 32"),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_DYNAMIC_MEMORY_PROTECTION_ID,
            __MEDIA_USER_FEATURE_VALUE_DYNAMIC_MEMORY_PROTECTION,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            "Report",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_UINT32,
            "0",
            "User feature that highlights Memory Protection type. Lite: 0. Heavy: 1."),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_REPORT_FRAMES_ENCRYPTED_ID,
            __MEDIA_USER_FEATURE_VALUE_REPORT_FRAMES_ENCRYPTED,
            __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            "Report",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_UINT32,
            "0",
            "Not Reported : Can be used as a debug feature, when this is set to 1.."),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_FRAMES_ENCRYPTED_ID,
            __MEDIA_USER_FEATURE_VALUE_FRAMES_ENCRYPTED,
            __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            "Report",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_UINT32,
            "0",
            "Not Reported : Need to enable Report Encrypted Frame Count "),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_PROTECTION_TRIGGERED_ID,
            __MEDIA_USER_FEATURE_VALUE_PROTECTION_TRIGGERED,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            "Report",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_UINT32,
            "0",
            "Used in Screen Capture Defense Test"),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_AUTO_TEAR_DOWN_COUNTER_ID,
            __MEDIA_USER_FEATURE_VALUE_AUTO_TEAR_DOWN_COUNTER,
            __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            "Report",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_BOOL,
            "0",
            "Not reported : Tested on 15.33 and 15.36 HSW"),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_LITE_SESSIONS_ID,
            __MEDIA_USER_FEATURE_VALUE_LITE_SESSIONS,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            "Report",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_UINT32,
            "0",
            "No of Lite mode sessions currently active Value : 1."),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_HEAVY_SESSIONS_ID,
            __MEDIA_USER_FEATURE_VALUE_HEAVY_SESSIONS,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            "Report",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_UINT32,
            "0",
            "No of heavy  mode sessions currently active Value : 1."),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_RSA_COUNT_ID,
            __MEDIA_USER_FEATURE_VALUE_RSA_COUNT,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            "Report",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_UINT32,
            "0",
            "Need to enable MOS user feature key to get this value in report. ."),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_COUNTER_TYPE_ID,
            __MEDIA_USER_FEATURE_VALUE_COUNTER_TYPE,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            "Report",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_UINT32,
            "0",
            "Used in : HSW (Mobile and Desktop) Type A : 1 Type B : 2 Type C : 4."),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_PAVP_KEY_REFRESH_MODE_ID,
            __MEDIA_USER_FEATURE_VALUE_PAVP_KEY_REFRESH_MODE,
            __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            "Media",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_INT32,
            "0",  // Default is 0 which is Daisy chain key refresh
            "Id of PAVP Key Refresh Mode"),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_PAVP_NON_ZERO_CEK_ID,
            __MEDIA_USER_FEATURE_VALUE_PAVP_NON_ZERO_CEK,
            __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            "Media",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_INT32,
            "0",  // Default is 0 which is zero CEK
            "Id of PAVP Use NonZero CEK"),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_PAVP_NON_ZERO_WIDI_KS_ID,
            __MEDIA_USER_FEATURE_VALUE_PAVP_NON_ZERO_WIDI_KS,
            __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            "Media",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_INT32,
            "0",  // Default is 0 which is zero CEK
            "Id of PAVP Use NonZero Widi Session Key Ks"),
#if (_DEBUG || _RELEASE_INTERNAL)
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_PAVP_FORCE_LITE_MODE_FOR_DEBUG_ID,
            __MEDIA_USER_FEATURE_VALUE_PAVP_FORCE_LITE_MODE_FOR_DEBUG,
            __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            "Media",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_INT32,
            "0",  // Default is 0, which is disabled.
            "Id of PAVP Force Lite Mode For Debug"),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_PAVP_LITE_MODE_ENABLE_HUC_STREAMOUT_FOR_DEBUG_ID,
                __MEDIA_USER_FEATURE_VALUE_PAVP_LITE_MODE_ENABLE_HUC_STREAMOUT_FOR_DEBUG,
                __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
                __MEDIA_USER_FEATURE_SUBKEY_REPORT,
                "Media",
                MOS_USER_FEATURE_TYPE_USER,
                MOS_USER_FEATURE_VALUE_TYPE_INT32,
                "0",  // Default is 0, which is disabled.
                "Id of PAVP Lite Mode Enable Huc StreamOut For Debug"),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_PAVP_GSC_TUNNELING_SUPPORTED_ID,
            __MEDIA_USER_FEATURE_VALUE_PAVP_GSC_TUNNELING_SUPPORTED,
            __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            "Media",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_INT32,
            "0",  // Default is 0, which is disabled.
            "Id of PAVP GSC Tunneling Supported on ICL For Testing"),
            MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_PAVP_GSC_EMULATION_ID,
                __MEDIA_USER_FEATURE_VALUE_PAVP_GSC_EMULATION,
                __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
                __MEDIA_USER_FEATURE_SUBKEY_REPORT,
                "Media",
                MOS_USER_FEATURE_TYPE_USER,
                MOS_USER_FEATURE_VALUE_TYPE_INT32,
                "0",  // Default is 0, which is disabled.
                "Id of TEST ENVIRONMENT IS PAVP GSC EMULATION"),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_PAVP_SKIP_CHECK_PCH_PRODUCT_FAMILIY_ID,
            __MEDIA_USER_FEATURE_VALUE_PAVP_SKIP_CHECK_PCH_PRODUCT_FAMILIY,
            __MEDIA_USER_FEATURE_SUBKEY_PERMANENT,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            "Media",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_INT32,
            "0",  // Default is 0, which is disabled.
            "Id of PAVP Skip PCH product family"),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_PAVP_DECODE_USE_HUC_DECRYPT_ID,
            __MEDIA_USER_FEATURE_VALUE_PAVP_DECODE_USE_HUC_DECRYPT,
            __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            "Media",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_INT32,
            "0",  // Default is 0, which is disabled.
            "Id of PAVP decode use HuC for stream decryption"),
#endif
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_PAVP_HUC_ACCESS_TO_ENCR_BITSTREAM_ID,
            __MEDIA_USER_FEATURE_VALUE_PAVP_HUC_ACCESS_TO_ENCR_BITSTREAM,
            __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            "Media",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_INT32,
            "0",  // Default is 0 which is allow HuC access to encrypted bitstream
            "Id of PAVP HuC Access Ctrl"),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_PAVP_ENCRYPT_HUC_WRITE_TO_R15_ID,
            __MEDIA_USER_FEATURE_VALUE_PAVP_ENCRYPT_HUC_WRITE_TO_R15,
            __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            "Media",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_INT32,
            "0",  // Default is 0 which is allow HuC clear writes to region 15
            "Id of PAVP HuC R15 Ctrl"),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_PAVP_ENCRYPT_CC_CTRL_ID,
            __MEDIA_USER_FEATURE_VALUE_PAVP_ENCRYPT_CC_CTRL,
            __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            "Media",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_INT32,
            "0",  // Default is 0 which is allow Encrypt cryto copy modes 2,4,7
            "Id of PAVP Encrypt CC Ctrl"),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_PAVP_DECRYPT_CC_CTRL_ID,
            __MEDIA_USER_FEATURE_VALUE_PAVP_DECRYPT_CC_CTRL,
            __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            "Media",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_INT32,
            "0",  // Default is 0 which is allow Decrypt cryto copy modes 2,3,d
            "Id of PAVP Decrypt CC Ctrl"),
        MOS_DECLARE_UF_KEY(__MEDIA_USER_FEATURE_VALUE_PAVP_ALLOW_PROGRAMMABLE_AES_COUNTER_ID,
            __MEDIA_USER_FEATURE_VALUE_PAVP_ALLOW_PROGRAMMABLE_AES_COUNTER,
            __MEDIA_USER_FEATURE_SUBKEY_INTERNAL,
            __MEDIA_USER_FEATURE_SUBKEY_REPORT,
            "Media",
            MOS_USER_FEATURE_TYPE_USER,
            MOS_USER_FEATURE_VALUE_TYPE_INT32,
            "0",  // Default is 0, which is to ignore AES counter programmed by driver.
            "Id of PAVP Allow Programmable AES Counter"),
};

CpUserSettingsMgr::CpUserSettingsMgr()
{
    MOS_STATUS eStatus = MosUtilities::MosDeclareUserFeatureKeysFromDescFields(
        cpUserFeatureKeyDescFields,
        CP_NUM_USERFEATURE_KEY_VALUES,
        __CP_USER_FEATURE_KEY_MAX_ID);

    if (MOS_FAILED(eStatus))
    {
        CP_ASSERTMESSAGE(MOS_CP_SUBCOMP_OS, "CP util user feature key init error");
    }
}

CpUserSettingsMgr::~CpUserSettingsMgr()
{
    MOS_STATUS eStatus = MosUtilities::MosDestroyUserFeatureKeysFromDescFields(
        cpUserFeatureKeyDescFields,
        CP_NUM_USERFEATURE_KEY_VALUES,
        __CP_USER_FEATURE_KEY_MAX_ID);

    if (MOS_FAILED(eStatus))
    {
        CP_ASSERTMESSAGE(MOS_CP_SUBCOMP_OS, "CP util user feature key destroy error");
    }
}
